# Generated by Django 2.2.12 on 2020-08-18 08:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='name',
        ),
        migrations.AddField(
            model_name='comment',
            name='email',
            field=models.EmailField(default=datetime.datetime(2020, 8, 18, 8, 53, 30, 875463, tzinfo=utc), max_length=254),
            preserve_default=False,
        ),
    ]
